//employee
export const SET_EMPLOYEES = "SET_EMPLOYEES";
export const DELETE_EMPLOYEES_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const SET_UPDATING_EMPLOYEE = "SET_UPDATING_EMPLOYEE";
export const SUBMIT_EMPLOYEE_SUCCESS = "SUBMIT_EMPLOYEE_SUCCSESS";

//location
export const SET_UFS = "SET_UFS";
export const SET_CITIES = "SET_CITIES";
